// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGlucjtgfw6h21qv-UedJhDPjHvk9aNRA',
    appId: '1:428062798858:web:a02ea6f4d8b8f462449bf3',
    messagingSenderId: '428062798858',
    projectId: 'cards1-33dbf',
    authDomain: 'cards1-33dbf.firebaseapp.com',
    databaseURL: 'https://cards1-33dbf-default-rtdb.firebaseio.com',
    storageBucket: 'cards1-33dbf.appspot.com',
    measurementId: 'G-T4CPN0TB3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPovyQGwwRlPEKLGiWh4EEOguzemPLItM',
    appId: '1:428062798858:android:8ebffd2a12330d33449bf3',
    messagingSenderId: '428062798858',
    projectId: 'cards1-33dbf',
    databaseURL: 'https://cards1-33dbf-default-rtdb.firebaseio.com',
    storageBucket: 'cards1-33dbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpLbuf5ffJpKXEJReLvBj1kSJJfU9jPfs',
    appId: '1:428062798858:ios:b9d039b06730e9ee449bf3',
    messagingSenderId: '428062798858',
    projectId: 'cards1-33dbf',
    databaseURL: 'https://cards1-33dbf-default-rtdb.firebaseio.com',
    storageBucket: 'cards1-33dbf.appspot.com',
    iosClientId: '428062798858-u1je6stcjkt69bv2eofoof7r67c6kebo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cards2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpLbuf5ffJpKXEJReLvBj1kSJJfU9jPfs',
    appId: '1:428062798858:ios:b9d039b06730e9ee449bf3',
    messagingSenderId: '428062798858',
    projectId: 'cards1-33dbf',
    databaseURL: 'https://cards1-33dbf-default-rtdb.firebaseio.com',
    storageBucket: 'cards1-33dbf.appspot.com',
    iosClientId: '428062798858-u1je6stcjkt69bv2eofoof7r67c6kebo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cards2App',
  );
}
